# Generated by Django 2.2.3 on 2019-10-22 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import sharing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('building', models.CharField(blank=True, max_length=10, null=True)),
                ('flat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('BLOCKED', 'Заблокирована'), ('RENTED', 'Арендована'), ('BUCHEN', 'Забронирована'), ('U', 'Свободна')], max_length=10, null=True)),
                ('door_status', models.BooleanField(blank=True, choices=[('B', 'Заблокирована'), ('U', 'Доступ открыт')], null=True)),
                ('cleaning_time', models.TimeField(blank=True, default='3:00', null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Districts')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Cities')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(choices=[(False, 'Не оплачен'), (True, 'Оплачен')], default=False, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('P', 'Подтверждение аккаунта'), ('D', 'Депозит'), ('F', 'Полная стоимость')], default='D', max_length=1, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Транзакция Yandex',
                'verbose_name_plural': 'Транзакции Yandex',
            },
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало аренды')),
                ('end', models.DateTimeField(verbose_name='Окончание аренды')),
                ('status', models.BooleanField(default=False, null=True)),
                ('paid', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(default=False, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Квартира', related_query_name='Квартира', to='sharing.Flats')),
                ('rentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-start'],
            },
            managers=[
                ('renta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Оператор'), (2, 'Клининг'), (3, 'Мастер')])),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Partners')),
            ],
            options={
                'verbose_name': 'Сотрудник партнёра',
                'verbose_name_plural': 'Сотрудники партнёров',
            },
        ),
        migrations.CreateModel(
            name='UsersDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(default='', max_length=50, verbose_name='Мобильный номер')),
                ('image_one', models.ImageField(default=None, upload_to=sharing.models.get_file_path_users, verbose_name='Фотография первой страницы паспорта')),
                ('image_two', models.ImageField(default=None, upload_to=sharing.models.get_file_path_users, verbose_name='Фотография страницы с пропиской')),
                ('status', models.BooleanField(choices=[(False, 'Не подтверждён'), (True, 'Подтверждён')], default=False)),
                ('yakey', models.CharField(default=None, max_length=50, null=True)),
                ('totlal_cancelation', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документы пользователей',
                'verbose_name_plural': 'Документы пользователей',
            },
        ),
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Districts')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Flats')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Partners')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Payments')),
                ('rents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Rents')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Workers')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='renta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Rents'),
        ),
        migrations.AddField(
            model_name='payments',
            name='rentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=sharing.models.get_file_path)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Flats')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='districts',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Partners'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Countries'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('used', models.IntegerField(blank=True, default=0, null=True)),
                ('renta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Rents')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
