# Generated by Django 2.2.3 on 2019-09-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flats',
            name='partner',
        ),
    ]
