# Generated by Django 2.2.7 on 2019-11-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20191113_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlogs',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
