# Generated by Django 2.2.3 on 2019-09-18 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0003_remove_flats_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Транзакция Yandex', 'verbose_name_plural': 'Транзакции Yandex'},
        ),
        migrations.AlterModelOptions(
            name='rents',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Сотрудник партнёра', 'verbose_name_plural': 'Сотрудники партнёров'},
        ),
        migrations.AlterField(
            model_name='flats',
            name='door_status',
            field=models.BooleanField(blank=True, choices=[('B', 'Заблокирована'), ('U', 'Доступ открыт')], null=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='status',
            field=models.BooleanField(blank=True, choices=[('B', 'Заблокирована'), ('U', 'Доступ открыт')], null=True),
        ),
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
