# Generated by Django 2.2.7 on 2019-11-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_systemlogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlogs',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
