# Generated by Django 2.2.3 on 2019-09-18 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_auto_20190918_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlogs',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Districts'),
        ),
        migrations.AddField(
            model_name='systemlogs',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Flats'),
        ),
        migrations.AddField(
            model_name='systemlogs',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Partners'),
        ),
        migrations.AddField(
            model_name='systemlogs',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Payments'),
        ),
        migrations.AddField(
            model_name='systemlogs',
            name='rents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Rents'),
        ),
        migrations.AddField(
            model_name='systemlogs',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Workers'),
        ),
        migrations.AlterField(
            model_name='systemlogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
