# Generated by Django 2.2.7 on 2019-11-23 12:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_systemlogs_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='access',
            managers=[
                ('access', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Подтверждение аккаунта'), (1, 'Депозит'), (2, 'Полная стоимость')], default=0, null=True),
        ),
    ]
