# Generated by Django 2.2.7 on 2019-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_auto_20191123_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='ya_card_last4',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='usersdocuments',
            name='ya_card_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
