# Generated by Django 2.2.3 on 2019-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_auto_20190918_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
