# Generated by Django 2.2.7 on 2019-12-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_auto_20191130_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='rents',
            name='trial_key',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
