# Generated by Django 2.2.3 on 2019-09-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0009_auto_20190918_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='captured_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
