# Generated by Django 2.2.3 on 2019-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0010_auto_20190918_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.BooleanField(blank=True, choices=[('D', 'Депозит'), ('F', 'Полная стоимость')], null=True),
        ),
    ]
