# Generated by Django 2.2.3 on 2019-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0011_payments_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('D', 'Депозит'), ('F', 'Полная стоимость')], default='D', max_length=1, null=True),
        ),
    ]
