# Generated by Django 2.2.3 on 2019-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0013_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='rents',
            name='deposit',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
