# Generated by Django 2.2.3 on 2019-09-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0014_auto_20190919_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='flat',
        ),
        migrations.AddField(
            model_name='access',
            name='renta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Rents'),
        ),
    ]
