# Generated by Django 2.2.3 on 2019-09-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0015_auto_20190919_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='access',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
    ]
