# Generated by Django 2.2.3 on 2019-09-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0016_auto_20190919_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rents',
            options={'ordering': ['-start'], 'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterField(
            model_name='rents',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Квартира', related_query_name='Квартира', to='sharing.Flats'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
