# Generated by Django 2.2.3 on 2019-09-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0017_auto_20190920_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='cleaning_time',
            field=models.TimeField(blank=True, default='3:00', null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание аренды'),
        ),
        migrations.AddField(
            model_name='payments',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало аренды'),
        ),
    ]
