# Generated by Django 2.2.3 on 2019-09-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0018_auto_20190921_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='end',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='start',
        ),
        migrations.RemoveField(
            model_name='rents',
            name='payment',
        ),
        migrations.AddField(
            model_name='payments',
            name='renta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Rents'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.BooleanField(choices=[(False, 'Не оплачен'), (True, 'Оплачен')], default=False, null=True),
        ),
    ]
