# Generated by Django 2.2.3 on 2019-09-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0019_auto_20190921_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
