# Generated by Django 2.2.3 on 2019-09-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sharing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0020_access_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to=sharing.models.get_file_path_users)),
                ('image_two', models.ImageField(blank=True, null=True, upload_to=sharing.models.get_file_path_users)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документы пользователей',
                'verbose_name_plural': 'Документы пользователей',
            },
        ),
    ]
