# Generated by Django 2.2.3 on 2019-09-24 16:12

from django.db import migrations, models
import sharing.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0021_usersdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='image_one',
            field=models.ImageField(default=None, upload_to=sharing.models.get_file_path_users),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='image_two',
            field=models.ImageField(default=None, upload_to=sharing.models.get_file_path_users),
        ),
    ]
