# Generated by Django 2.2.3 on 2019-09-24 16:45

from django.db import migrations, models
import sharing.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0022_auto_20190924_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='status',
            field=models.BooleanField(choices=[(False, 'Не подтвержден'), (True, 'Подтверждён')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='image_one',
            field=models.ImageField(default=None, upload_to=sharing.models.get_file_path_users, verbose_name='Фотография первой страницы паспорта'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='image_two',
            field=models.ImageField(default=None, upload_to=sharing.models.get_file_path_users, verbose_name='Фотография страницы с пропиской'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мобильный номер'),
        ),
    ]
