# Generated by Django 2.2.3 on 2019-09-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0023_auto_20190924_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='firstname',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='lastname',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='Мобильный номер'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='status',
            field=models.BooleanField(choices=[(False, 'Не подтвержден'), (True, 'Подтверждён')], default=False),
        ),
    ]
