# Generated by Django 2.2.3 on 2019-09-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0024_auto_20190924_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='status',
            field=models.CharField(blank=True, choices=[('B', 'Заблокирована'), ('R', 'Арендована'), ('U', 'Свободна')], max_length=10, null=True),
        ),
    ]
