# Generated by Django 2.2.3 on 2019-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0025_auto_20190928_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='status',
            field=models.CharField(blank=True, choices=[('BLOCKED', 'Заблокирована'), ('RENTED', 'Арендована'), ('BUCHEN', 'Забронирована'), ('U', 'Свободна')], max_length=10, null=True),
        ),
    ]
