# Generated by Django 2.2.3 on 2019-09-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0026_auto_20190928_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='yakey',
            field=models.CharField(default='', max_length=50),
        ),
    ]
