# Generated by Django 2.2.3 on 2019-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0028_auto_20191002_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('P', 'Подтверждение аккаунта'), ('D', 'Депозит'), ('F', 'Полная стоимость')], default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='agreement',
            field=models.BooleanField(choices=[(False, 'Не согласен'), (True, 'Согласен')], verbose_name='Согласие с лицензионным соглашением'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='yakey',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
