# Generated by Django 2.2.3 on 2019-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0029_auto_20191002_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='yakey',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
