# Generated by Django 2.2.3 on 2019-10-05 10:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0030_auto_20191002_2059'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rents',
            managers=[
                ('renta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='rents',
            name='cleaned',
        ),
        migrations.RemoveField(
            model_name='rents',
            name='deposit',
        ),
        migrations.AddField(
            model_name='rents',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
