# Generated by Django 2.2.3 on 2019-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0031_auto_20191005_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='role',
            field=models.IntegerField(choices=[(1, 'Оператор'), (2, 'Клининг'), (3, 'Мастер')]),
        ),
    ]
